### ISSUE TITLE
Add dependabot configuration

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-database-connectors#17]
As per https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates we should create a dependabot.yml

Egeria has one in .github/dependabot.yml and I suspect just the following will work:
```
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 100
  reviewers:
  - planetf1
  - wbittles
```
We only do monthly for egeria, which is forced to 1st of the month. This cannot be changed. perhaps with less dependencies we go for a more regular or daily check which at least will pick up egeria itself etc.
